Working craft

diff --git a/craft b/craft
--- a/craft
+++ b/craft
@@ -2,12 +2,24 @@
 # shellcheck disable=SC1091
 
 # Oct 26
-YQ_RELEASE=v4.44.3
-KIND_RELEASE=v0.24.0
+YQ_RELEASE=v4.44.6
+KIND_RELEASE=v0.26.0
 GOLANG_RELEASE=1.23.3
-HELM_RELEASE=v3.16.2
+HELM_RELEASE=v3.17.0
 
 source .pretty_print
+
+if [[ -z "${RF_CRAFT_HOST}" ]]; then
+    echo "Error: RF_CRAFT_HOST is not set. VM's internal or external ip address. Exiting..."
+    exit 1
+fi
+
+echo "RF_CRAFT_HOST is set to: ${RF_CRAFT_HOST}"
+
+if [[ -z "${QUAY_CRAFT}" ]]; then
+    echo "Error: QUAY_CRAFT is not set. Exiting..."
+    exit 1
+fi
 
 get_os_str()
 {
@@ -193,14 +205,13 @@ kubectl_install()
 websocat_install()
 {
     if [[ "$(get_architecture_alt)" == "aarch64" || "$(get_architecture)" == "arm64" ]]; then
-        echo skip installing websocat
+        print_bred "skip installing websocat, websocat required for coverage tests"
     else
         local url="https://github.com/vi/websocat/releases/download/v1.13.0/websocat.$(get_architecture)-unknown-$(get_os_str)-musl"
         if ! curl --output /dev/null --silent --head --fail -L "$url"; then
             url="https://github.com/vi/websocat/releases/download/v1.13.0/websocat.$(get_architecture_alt)-unknown-$(get_os_str)-musl"
         fi
 
-        # Download and install
         curl -sL "$url" -o /usr/local/bin/websocat
         chmod +x /usr/local/bin/websocat
         websocat --version
@@ -359,19 +370,23 @@ init()
             if [ "$ID" = "debian" ] || [ "$ID" = "ubuntu" ]; then
                 run_command debian_init
                 if [ "$ID" = "ubuntu" ]; then
-                    systemctl stop snapd || true
-                    systemctl disable snapd || true
-                    snap remove --purge $(snap list | awk 'NR>1 {print $1}') || true
-                    apt purge snapd -y || true
-                    rm -rf /var/cache/snapd
-                    rm -rf /var/snap
-                    rm -rf ~/snap
-                    systemctl stop multipathd || true
-                    systemctl disable multipathd || true
-                    apt purge multipath-tools -y
-                    rm -rf /etc/multipath
-                    rm -f /etc/multipath.conf
-                    update-initramfs -u
+                    if command -v snap &>/dev/null; then
+                        systemctl stop snapd || true
+                        systemctl disable snapd || true
+                        snap remove --purge $(snap list | awk 'NR>1 {print $1}') || true
+                        apt purge snapd -y || true
+                        rm -rf /var/cache/snapd
+                        rm -rf /var/snap
+                        rm -rf ~/snap
+                    fi
+                    if command -v multipath &>/dev/null; then
+                        systemctl stop multipathd || true
+                        systemctl disable multipathd || true
+                        apt purge multipath-tools -y
+                        rm -rf /etc/multipath
+                        rm -f /etc/multipath.conf
+                        update-initramfs -u
+                   fi
                 fi
             elif [ "$ID" = "rhel" ] || [ "$ID" = "centos" ] || [ "$ID" = "fedora" ]; then
                 run_command rhel_init
@@ -445,9 +460,9 @@ init()
     cp -vf RF_* /root/rapidfort
 }
 
-setup_local_registry()
+setup_craft()
 {
-    export REGISTRY_NAME="${RF_APP_HOST}:5000"
+    export REGISTRY_NAME="${RF_CRAFT_HOST}:5000"
 
     print_bgreen "Allow insecure registry"
 
@@ -470,14 +485,28 @@ setup_local_registry()
 
     test -s kind/kind-config.yaml || cp -vf kind/kind-config.yaml.template kind/kind-config.yaml
     export OLDIP=$(grep :5000 kind/kind-config.yaml | sed "s=:5000.*==g" | rev | sed 's/[^0123456789.].*//' | rev | sort | uniq | head -1)
-    sed -i "s=${OLDIP}:5000=${RF_APP_HOST}:5000=g" kind/kind-config.yaml
+    sed -i "s=${OLDIP}:5000=${RF_CRAFT_HOST}:5000=g" kind/kind-config.yaml
+
+    # Delete all existing clusters if exists
+
+    CLUSTERS=("craft" "platform")
+
+    for cluster in "${CLUSTERS[@]}"; do
+        echo "Deleting Kind cluster: $cluster..."
+        kind delete cluster --name "$cluster"
+    done
+
+    while kind get clusters | grep -q "^$cluster$"; do
+        echo "Waiting for cluster '$cluster' to be fully deleted..."
+        sleep 1
+    done
 
     export SUCCESS=0
     export RETRIES=8
 
     while [ ${RETRIES} -gt 0 ]; do
-        echo "Create cluster platform"
-        if kind create cluster --name platform --config kind/kind-config.yaml --wait 8m; then
+        echo "Create cluster craft"
+        if kind create cluster --name craft --config kind/kind-config.yaml --wait 8m; then
             export SUCCESS=1
             export RETRIES=0
         else
@@ -492,30 +521,33 @@ setup_local_registry()
         exit 1
     fi
 
-    echo "Setup local registry"
     if test ! -d common/registry/certs; then
         print_bgreen "Generating certs"
         mkdir -p common/registry/certs
         openssl req \
             -newkey rsa:4096 -nodes -sha256 -keyout common/registry/certs/registry.key \
-            -addext "subjectAltName = IP:$RF_APP_HOST" \
+            -addext "subjectAltName = IP:$RF_CRAFT_HOST" \
             -x509 -days 3650 -out common/registry/certs/registry.crt \
             -subj "/C=US/ST=CA/L=SANFRANCISCO/O=RapidFort Inc/OU=Engineering/CN=rapidfort.com"
 
         if [ -f /etc/redhat-release ]; then
             [ -d "/etc/pki/ca-trust/source/whitelist" ] || mkdir -p "/etc/pki/ca-trust/source/whitelist"
             cp -vf common/registry/certs/registry.crt /etc/pki/ca-trust/source/whitelist/registry.crt
-            update-ca-trust
+            update-ca-trust || true
         else
             cp -vf common/registry/certs/registry.crt /usr/local/share/ca-certificates/registry.crt
-            update-ca-certificates
+            update-ca-certificates || true
         fi
     fi
-}
 
-deploy_bpf_agent()
-{
-    :
+    pushd common
+        print_bgreen "Setup registry"
+        helm upgrade --install registry registry --wait --timeout 1200s
+    popd
+
+    sed -i "s|^imagePullSecrets: .*|imagePullSecrets: ${QUAY_CRAFT}|" override.yaml
+
+    helm upgrade --install rapidfort oci://quay.io/rapidfort/runtime -f override.yaml
 }
 
 # Allow individual updates via command-line argument
@@ -537,11 +569,11 @@ if [ -n "$1" ]; then
         gcp) run_command gcp_install ;;
         k3s) run_command k3s_install ;;
         update) init "update" ;;
+        init) setup_craft ;;
         *) echo "Unknown command: $1" ;;
     esac
 else
     init
+    setup_craft
 fi
 
-setup_local_registry
-deploy_bpf_agent
